import { Loan } from '@/@types/entities/loan';

export const mockLoanData = [
  {
    id: '1',
    personId: '1',
    amount: 1000,
    installmentsQty: 12,
    status: 'pending',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    person: {
      name: 'John Doe',
      identification: '123456789',
      birthdate: new Date().toISOString(),
      identificationType: 'naturalPerson',
      minimumMonthAmount: 100,
      maximumTotalAmount: 10000,
    },
    installments: [
      {
        id: '1',
        amount: 100,
        dueDate: new Date().toISOString(),
        status: 'pending',
        loanId: '1',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: '2',
        amount: 100,
        dueDate: new Date().toISOString(),
        status: 'pending',
        loanId: '1',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  {
    id: '2',
    personId: '2',
    amount: 500,
    installmentsQty: 6,
    status: 'paid',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    person: {
      name: 'Jane Doe',
      identification: '987654321',
      birthdate: new Date().toISOString(),
      identificationType: 'legalPerson',
      minimumMonthAmount: 50,
      maximumTotalAmount: 5000,
    },
    installments: [
      {
        id: '3',
        amount: 100,
        dueDate: new Date().toISOString(),
        status: 'paid',
        loanId: '2',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: '4',
        amount: 100,
        dueDate: new Date().toISOString(),
        status: 'paid',
        loanId: '2',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: '5',
        amount: 100,
        dueDate: new Date().toISOString(),
        status: 'paid',
        loanId: '2',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  {
    id: '3',
    personId: '3',
    amount: 2000,
    installmentsQty: 24,
    status: 'pending',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    person: {
      name: 'John Doe',
      identification: '123456789',
      birthdate: new Date().toISOString(),
      identificationType: 'student',
      minimumMonthAmount: 200,
      maximumTotalAmount: 20000,
    },
    installments: [
      {
        id: '6',
        amount: 100,
        dueDate: new Date().toISOString(),
        status: 'pending',
        loanId: '3',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: '7',
        amount: 100,
        dueDate: new Date().toISOString(),
        status: 'pending',
        loanId: '3',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
  {
    id: '4',
    personId: '4',
    amount: 300,
    installmentsQty: 3,
    status: 'paid',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    person: {
      name: 'Jane Doe',
      identification: '987654321',
      birthdate: new Date().toISOString(),
      identificationType: 'retiree',
      minimumMonthAmount: 30,
      maximumTotalAmount: 3000,
    },
    installments: [
      {
        id: '8',
        amount: 100,
        dueDate: new Date().toISOString(),
        status: 'paid',
        loanId: '4',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
  },
] as Loan[];
